package main

import "fmt"

//NOTE: go.mod file was generated by the command --> go mod init go_tutorials, but irl "go_tutorials" must be replaced by the repo's name

func main(){
	fmt.Println("Hello World")
}